---
apiVersion: network.openstack.org/v1beta1
kind: NetConfig
metadata:
  name: netconfig
  namespace: openstack
spec:
  networks:
  - dnsDomain: ctlplane.openstack.lab
    mtu: 1442
    name: ctlplane
    subnets:
    - allocationRanges:
      - end: 192.168.123.120
        start: 192.168.123.100
      - end: 192.168.123.200
        start: 192.168.123.150
      cidr: 192.168.123.0/24
      gateway: 192.168.123.1
      name: subnet1
    - allocationRanges:
      - end: 192.168.124.120
        start: 192.168.124.100
      - end: 192.168.124.200
        start: 192.168.124.150
      cidr: 192.168.124.0/24
      gateway: 192.168.124.1
      name: subnet2
    - allocationRanges:
      - end: 192.168.125.120
        start: 192.168.125.100
      - end: 192.168.125.200
        start: 192.168.125.150
      cidr: 192.168.125.0/24
      gateway: 192.168.125.1
      name: subnet3
      vlan: 19
  - dnsDomain: internalapi.openstack.lab
    mtu: 1442
    name: internalapi
    subnets:
    - allocationRanges:
      - end: 172.17.0.200
        start: 172.17.0.100
      cidr: 172.17.0.0/24
      name: subnet1
      vlan: 20
  - dnsDomain: storage.openstack.lab
    mtu: 1442
    name: storage
    subnets:
    - allocationRanges:
      - end: 172.18.0.200
        start: 172.18.0.100
      cidr: 172.18.0.0/24
      name: subnet1
      vlan: 21
  - dnsDomain: tenant.openstack.lab
    mtu: 1442
    name: tenant
    subnets:
    - allocationRanges:
      - end: 172.19.0.200
        start: 172.19.0.100
      cidr: 172.19.0.0/24
      name: subnet1
      vlan: 22
