apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  labels:
    osp/nncm-config-type: standard
  name: master-0
  namespace: openstack
spec:
  desiredState:
    dns-resolver:
      config:
        search: []
        server:
        - 192.168.32.3
    interfaces:
    - description: internalapi vlan interface
      ipv4:
        address:
        - ip: 172.17.0.5
          prefix-length: "24"
        dhcp: false
        enabled: true
      ipv6:
        enabled: false
      mtu: 1442
      name: internalapi
      state: up
      type: vlan
      vlan:
        base-iface: ens4
        id: "20"
    - description: storage vlan interface
      ipv4:
        address:
        - ip: 172.18.0.5
          prefix-length: "24"
        dhcp: false
        enabled: true
      ipv6:
        enabled: false
      mtu: 1442
      name: storage
      state: up
      type: vlan
      vlan:
        base-iface: ens4
        id: "21"
    - description: tenant vlan interface
      ipv4:
        address:
        - ip: 172.19.0.5
          prefix-length: "24"
        dhcp: false
        enabled: true
      ipv6:
        enabled: false
      mtu: 1442
      name: tenant
      state: up
      type: vlan
      vlan:
        base-iface: ens4
        id: "22"
    - description: ctlplane interface
      mtu: 1442
      name: ens4
      state: up
      type: ethernet
    - bridge:
        options:
          stp:
            enabled: false
        port:
        - name: ens4
          vlan: {}
      description: linux-bridge over ctlplane interface
      ipv4:
        address:
        - ip: 192.168.122.10
          prefix-length: "24"
        dhcp: false
        enabled: true
      ipv6:
        enabled: false
      mtu: 1442
      name: ospbr
      state: up
      type: linux-bridge
    route-rules:
      config: []
    routes:
      config: []
  nodeSelector:
    kubernetes.io/hostname: master-0
    node-role.kubernetes.io/worker: ""
---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  labels:
    osp/nncm-config-type: standard
  name: master-1
  namespace: openstack
spec:
  desiredState:
    dns-resolver:
      config:
        search: []
        server:
        - 192.168.32.3
    interfaces:
    - description: internalapi vlan interface
      ipv4:
        address:
        - ip: 172.17.0.6
          prefix-length: "24"
        dhcp: false
        enabled: true
      ipv6:
        enabled: false
      mtu: 1442
      name: internalapi
      state: up
      type: vlan
      vlan:
        base-iface: ens4
        id: "20"
    - description: storage vlan interface
      ipv4:
        address:
        - ip: 172.18.0.6
          prefix-length: "24"
        dhcp: false
        enabled: true
      ipv6:
        enabled: false
      mtu: 1442
      name: storage
      state: up
      type: vlan
      vlan:
        base-iface: ens4
        id: "21"
    - description: tenant vlan interface
      ipv4:
        address:
        - ip: 172.19.0.6
          prefix-length: "24"
        dhcp: false
        enabled: true
      ipv6:
        enabled: false
      mtu: 1442
      name: tenant
      state: up
      type: vlan
      vlan:
        base-iface: ens4
        id: "22"
    - description: ctlplane interface
      mtu: 1442
      name: ens4
      state: up
      type: ethernet
    - bridge:
        options:
          stp:
            enabled: false
        port:
        - name: ens4
          vlan: {}
      description: linux-bridge over ctlplane interface
      ipv4:
        address:
        - ip: 192.168.122.11
          prefix-length: "24"
        dhcp: false
        enabled: true
      ipv6:
        enabled: false
      mtu: 1442
      name: ospbr
      state: up
      type: linux-bridge
    route-rules:
      config: []
    routes:
      config: []
  nodeSelector:
    kubernetes.io/hostname: master-1
    node-role.kubernetes.io/worker: ""
---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  labels:
    osp/nncm-config-type: standard
  name: master-2
  namespace: openstack
spec:
  desiredState:
    dns-resolver:
      config:
        search: []
        server:
        - 192.168.32.3
    interfaces:
    - description: internalapi vlan interface
      ipv4:
        address:
        - ip: 172.17.0.7
          prefix-length: "24"
        dhcp: false
        enabled: true
      ipv6:
        enabled: false
      mtu: 1442
      name: internalapi
      state: up
      type: vlan
      vlan:
        base-iface: ens4
        id: "20"
    - description: storage vlan interface
      ipv4:
        address:
        - ip: 172.18.0.7
          prefix-length: "24"
        dhcp: false
        enabled: true
      ipv6:
        enabled: false
      mtu: 1442
      name: storage
      state: up
      type: vlan
      vlan:
        base-iface: ens4
        id: "21"
    - description: tenant vlan interface
      ipv4:
        address:
        - ip: 172.19.0.7
          prefix-length: "24"
        dhcp: false
        enabled: true
      ipv6:
        enabled: false
      mtu: 1442
      name: tenant
      state: up
      type: vlan
      vlan:
        base-iface: ens4
        id: "22"
    - description: ctlplane interface
      mtu: 1442
      name: ens4
      state: up
      type: ethernet
    - bridge:
        options:
          stp:
            enabled: false
        port:
        - name: ens4
          vlan: {}
      description: linux-bridge over ctlplane interface
      ipv4:
        address:
        - ip: 192.168.122.12
          prefix-length: "24"
        dhcp: false
        enabled: true
      ipv6:
        enabled: false
      mtu: 1442
      name: ospbr
      state: up
      type: linux-bridge
    route-rules:
      config: []
    routes:
      config: []
  nodeSelector:
    kubernetes.io/hostname: master-2
    node-role.kubernetes.io/worker: ""
